[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sdv_doc_waterloo"
description = "Waterloo - Docstring Format and Tools"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Uwe (local workspace)" }]
license = "BSD-2-Clause"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Operating System :: OS Independent",
]
dynamic = ["version"]
dependencies = [
	]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
waterlint = "sdv.doc.waterloo.waterlint:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["sdv.doc.waterloo*"]

[tool.setuptools.dynamic]
version = { attr = "sdv.doc.waterloo.docitem_sphinx.__version__" }

[tool.setuptools.package-data]
"sdv.doc.waterloo" = [
  "py.typed",
  "mypy.ini",
  "_static/*.css"
]
